import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navber/Navbar";
import Footer from "@/Components/Footer/Footer";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DevZone IT",
  description: "Generated by abdurrahman482937",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="h-[100px] w-[100%] z-50">
            <Navbar></Navbar>
          </div>
          <div className="overflow-x-hidden">{children}</div>
          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
